/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package es.unavarra.iws.routerinstall.gui;

import es.unavarra.iws.routerinstall.engine.QueryManager;
import java.awt.Container;
import javax.swing.JOptionPane;

/**
 *
 * @author aqm
 */
public class Busqueda extends javax.swing.JPanel {
    
    QueryManager qm = null;

    /**
     * Creates new form Menu
     */
    public Busqueda(QueryManager qm) {
        this.qm = qm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbHome = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();
        jtBusqueda = new javax.swing.JTextField();
        jlError = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpContenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlBackground = new javax.swing.JLabel();

        setLayout(null);

        jbHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/home32.png"))); // NOI18N
        jbHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbHomeMouseClicked(evt);
            }
        });
        add(jbHome);
        jbHome.setBounds(420, 20, 50, 50);

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/search32.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbBuscarMouseClicked(evt);
            }
        });
        add(jbBuscar);
        jbBuscar.setBounds(360, 90, 110, 40);

        jtBusqueda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtBusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtBusquedaKeyTyped(evt);
            }
        });
        add(jtBusqueda);
        jtBusqueda.setBounds(20, 90, 330, 40);

        jlError.setForeground(new java.awt.Color(255, 0, 51));
        jlError.setText("No se encuentran resultados...");
        add(jlError);
        jlError.setBounds(20, 140, 200, 14);
        add(jSeparator1);
        jSeparator1.setBounds(-20, 170, 500, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/question32.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(10, 30, 30, 30);

        jLabel2.setBackground(new java.awt.Color(0, 102, 153));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("       Búsqueda de conceptos");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.black));
        jLabel2.setOpaque(true);
        add(jLabel2);
        jLabel2.setBounds(0, 20, 480, 50);

        jpContenido.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpContenido.setOpaque(false);

        jLabel1.setText("...");
        jpContenido.add(jLabel1);

        add(jpContenido);
        jpContenido.setBounds(10, 180, 460, 440);

        jlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/swr2.png"))); // NOI18N
        add(jlBackground);
        jlBackground.setBounds(0, 0, 480, 640);
    }// </editor-fold>//GEN-END:initComponents

    private void jbHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbHomeMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Container menu = this.getFocusCycleRootAncestor();
        Menu principal = new Menu(qm);
        menu.remove(this);
        principal.setSize(menu.getSize());
        menu.add(principal, 0);        
    }//GEN-LAST:event_jbHomeMouseClicked

    private void jbBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbBuscarMouseClicked
        busquedaconcepto(this.jtBusqueda.getText());
    }//GEN-LAST:event_jbBuscarMouseClicked

    private void jtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBusquedaKeyReleased
        /*
         * if(evt.getKeyCode()==KeyEvent.VK_ENTER &&
         * evt.getComponent().equals(this)){
         * busquedaRouter(this.jtBusqueda.getText());
        }
         */
    }//GEN-LAST:event_jtBusquedaKeyReleased

    private void jtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBusquedaKeyTyped
        if (jlError.isVisible()) {
            jlError.setVisible(false);
        }
    }//GEN-LAST:event_jtBusquedaKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbHome;
    private javax.swing.JLabel jlBackground;
    private javax.swing.JLabel jlError;
    private javax.swing.JPanel jpContenido;
    private javax.swing.JTextField jtBusqueda;
    // End of variables declaration//GEN-END:variables

    private void busquedaconcepto(String txtBusqueda) {
        String txtResultado;
        jlError.setVisible(false);
        if(!txtBusqueda.isEmpty()){
            txtResultado = qm.executeQueryBasicConcepts(txtBusqueda);
            if(txtResultado!=null && txtResultado.length()>0){
                    //JOptionPane.showMessageDialog(this, txtResultado,"Conceptos",JOptionPane.INFORMATION_MESSAGE);
                    if(txtResultado.toLowerCase().equals("microfiltro")){
                        jpContenido.removeAll();
                        jpContenido.add(new Cmicrofiltro());
                        jpContenido.revalidate();
                    }else if(txtResultado.toLowerCase().equals("ordenador")){
                        jpContenido.removeAll();
                        jpContenido.add(new Cordenador());
                        jpContenido.revalidate();
                    }else if(txtResultado.toLowerCase().equals("tarjetadered")){
                        jpContenido.removeAll();
                        jpContenido.add(new Ctarjetaderedv3());
                        jpContenido.revalidate();
                    }else 
                        JOptionPane.showMessageDialog(this, txtResultado,"Conceptos",JOptionPane.INFORMATION_MESSAGE);
                }
            else
                jlError.setVisible(true);
                
        }
    }
}
