/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package es.unavarra.iws.routerinstall.gui;

import javax.swing.ImageIcon;

/**
 *
 * @author aqm
 */
public class InstalacionGeneral extends javax.swing.JPanel {

    /**
     * Creates new form CConceptos
     */
    public InstalacionGeneral(String titulo, String comments) {
        initComponents();
        jlTitulo.setText(titulo);
        jtaComments.setText(comments);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaComments = new javax.swing.JTextArea();
        jlFondo = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(463, 435));
        setLayout(null);

        jlTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Titulo");
        jlTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jlTitulo);
        jlTitulo.setBounds(10, 20, 440, 23);

        jScrollPane1.setOpaque(false);

        jtaComments.setColumns(20);
        jtaComments.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jtaComments.setLineWrap(true);
        jtaComments.setRows(5);
        jtaComments.setWrapStyleWord(true);
        jtaComments.setOpaque(false);
        jScrollPane1.setViewportView(jtaComments);

        add(jScrollPane1);
        jScrollPane1.setBounds(15, 80, 430, 270);

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/vista_c.png"))); // NOI18N
        add(jlFondo);
        jlFondo.setBounds(0, 0, 463, 435);
    }// </editor-fold>//GEN-END:initComponents

    /** Returns an ImageIcon, or null if the path was invalid. */
    protected ImageIcon createImageIcon(String path,
                                           String description) {
    java.net.URL imgURL = getClass().getResource(path);
    if (imgURL != null) {
        return new ImageIcon(imgURL, description);
    } else {
        System.err.println("Couldn't find file: " + path);
        return null;
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlFondo;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextArea jtaComments;
    // End of variables declaration//GEN-END:variables
}
