/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package es.unavarra.iws.routerinstall.gui;

/**
 *
 * @author aqm
 */
public class Router1Panel3 extends javax.swing.JPanel {

    /**
     * Creates new form Router1Panel33
     */
    public Router1Panel3() {
        initComponents();
    }
    public void setProgressText(String s) {
        progressDescription.setText(s);
    }
    
    public void setProgressValue(int i) {
        progressSent.setValue(i);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTitulo = new javax.swing.JPanel();
        jlTexto = new javax.swing.JLabel();
        jlIcono = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jpContenido = new javax.swing.JPanel();
        jlTituloC = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        progressSent = new javax.swing.JProgressBar();
        progressDescription = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jpTitulo.setBackground(java.awt.Color.lightGray);
        jpTitulo.setLayout(new java.awt.BorderLayout());

        jlTexto.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jlTexto.setText("Conectar con el Router");
        jlTexto.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jpTitulo.add(jlTexto, java.awt.BorderLayout.CENTER);

        jlIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/key_orange32.png"))); // NOI18N
        jpTitulo.add(jlIcono, java.awt.BorderLayout.EAST);
        jpTitulo.add(jSeparator1, java.awt.BorderLayout.SOUTH);

        add(jpTitulo, java.awt.BorderLayout.NORTH);

        jpContenido.setLayout(new java.awt.BorderLayout());

        jlTituloC.setText("Intentando la conexión con el router");
        jpContenido.add(jlTituloC, java.awt.BorderLayout.NORTH);

        jLabel5.setText("Después de que el envío se ha completado, los botones Atrás y Finalizar le permitirá continuar");
        jpContenido.add(jLabel5, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));
        jPanel1.add(jLabel1);

        progressSent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        progressSent.setMaximumSize(new java.awt.Dimension(50, 19));
        progressSent.setPreferredSize(new java.awt.Dimension(100, 19));
        progressSent.setStringPainted(true);
        jPanel1.add(progressSent);

        progressDescription.setText("Conexión con el servidor ...");
        jPanel1.add(progressDescription);
        jPanel1.add(jLabel4);
        jPanel1.add(jLabel3);

        jpContenido.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(jpContenido, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlIcono;
    private javax.swing.JLabel jlTexto;
    private javax.swing.JLabel jlTituloC;
    private javax.swing.JPanel jpContenido;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JLabel progressDescription;
    private javax.swing.JProgressBar progressSent;
    // End of variables declaration//GEN-END:variables
}
