/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package es.unavarra.iws.routerinstall.gui;

import es.unavarra.iws.routerinstall.engine.QueryManager;
import java.awt.Container;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;

/**
 *
 * @author aqm
 */
public class Ayuda extends javax.swing.JPanel {
    
    QueryManager qm = null;
    
    /**
     * Creates new form Menu
     */
    public Ayuda(QueryManager qm) {
        this.qm = qm;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jtpAyuda = new javax.swing.JTabbedPane();
        jpPF = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaPF = new javax.swing.JTextArea();
        jpIN = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaIN = new javax.swing.JTextArea();
        jpPC = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtaPC = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jlTitulo = new javax.swing.JLabel();
        jlBackground = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/home32.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(420, 20, 50, 50);

        jtpAyuda.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jpPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpPF.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jpPF.setOpaque(false);
        jpPF.setLayout(new java.awt.BorderLayout());

        jtaPF.setColumns(20);
        jtaPF.setLineWrap(true);
        jtaPF.setRows(5);
        jtaPF.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jtaPF);

        jpPF.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jtpAyuda.addTab("Preguntas Frecuentes", new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/misc_03_16.png")), jpPF); // NOI18N

        jpIN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpIN.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jpIN.setOpaque(false);
        jpIN.setLayout(new java.awt.BorderLayout());

        jtaIN.setColumns(20);
        jtaIN.setLineWrap(true);
        jtaIN.setRows(5);
        jtaIN.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jtaIN);

        jpIN.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jtpAyuda.addTab("Incidencias", new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/misc_53_16.png")), jpIN); // NOI18N

        jpPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpPC.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jpPC.setOpaque(false);
        jpPC.setLayout(new java.awt.BorderLayout());

        jtaPC.setColumns(20);
        jtaPC.setLineWrap(true);
        jtaPC.setRows(5);
        jtaPC.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jtaPC);

        jpPC.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jtpAyuda.addTab("Problemas comunes", new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/misc_13_16.png")), jpPC); // NOI18N

        add(jtpAyuda);
        jtpAyuda.setBounds(30, 100, 420, 440);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/help32.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(10, 30, 30, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/note_search32.png"))); // NOI18N
        jButton2.setText("Actualizar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(330, 570, 120, 40);

        jlTitulo.setBackground(new java.awt.Color(0, 51, 102));
        jlTitulo.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlTitulo.setText("       Ayuda");
        jlTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0)));
        jlTitulo.setOpaque(true);
        add(jlTitulo);
        jlTitulo.setBounds(0, 20, 480, 50);

        jlBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/swr2.png"))); // NOI18N
        add(jlBackground);
        jlBackground.setBounds(0, 0, 480, 660);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Container menu = this.getFocusCycleRootAncestor();
        Menu principal = new Menu(qm);
        menu.remove(this);
        principal.setSize(menu.getSize());
        menu.add(principal, 0);        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String sResultado = "";
        List<String> list = new ArrayList<String>();
        Random r = new Random();
        
        int sel = jtpAyuda.getSelectedIndex(); 
        if(sel==0){
            list = qm.getAvailableRouters();
            Iterator iter = list.iterator();
            while (iter.hasNext()){
                sResultado += (iter.next() + "\n\n");
            }
            jtaPF.setText(sResultado);
        }else if(sel==1){
            jtaIN.setText("\nIncidencias: " + (r.nextInt(10)+1) );
        }else if(sel==2){
            jtaPC.setText("\nProblemas comunes: " + (r.nextInt(10)+1) );
        }
            
    }//GEN-LAST:event_jButton2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jlBackground;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JPanel jpIN;
    private javax.swing.JPanel jpPC;
    private javax.swing.JPanel jpPF;
    private javax.swing.JTextArea jtaIN;
    private javax.swing.JTextArea jtaPC;
    private javax.swing.JTextArea jtaPF;
    private javax.swing.JTabbedPane jtpAyuda;
    // End of variables declaration//GEN-END:variables
}
