/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package es.unavarra.iws.routerinstall.gui;

/**
 *
 * @author aqm
 */
public class Rct351Panel1 extends javax.swing.JPanel {

    /**
     * Creates new form Rct351Panel1
     */
    public Rct351Panel1(String primerPaso) {
        initComponents();
        this.jlPrimerPaso.setText(primerPaso);
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconoLabel = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        ContenidoTodo = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        ContenidoTexto = new javax.swing.JPanel();
        jlSeparador = new javax.swing.JLabel();
        jlImagenRouter = new javax.swing.JLabel();
        jlSeparador2 = new javax.swing.JLabel();
        jlTexto = new javax.swing.JLabel();
        jlPrimerPaso = new javax.swing.JLabel();
        jlSeparador3 = new javax.swing.JLabel();
        jlSiguiente = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        iconoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/r_movistar.jpg"))); // NOI18N
        iconoLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        add(iconoLabel, java.awt.BorderLayout.WEST);

        Contenido.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        Contenido.setLayout(new java.awt.BorderLayout());

        ContenidoTodo.setLayout(new java.awt.BorderLayout());

        lTitulo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lTitulo.setText("Instalación del Router CT-351");
        ContenidoTodo.add(lTitulo, java.awt.BorderLayout.PAGE_START);

        ContenidoTexto.setLayout(new javax.swing.BoxLayout(ContenidoTexto, javax.swing.BoxLayout.Y_AXIS));

        jlSeparador.setMaximumSize(new java.awt.Dimension(257, 18));
        jlSeparador.setMinimumSize(new java.awt.Dimension(257, 18));
        ContenidoTexto.add(jlSeparador);

        jlImagenRouter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlImagenRouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/r_ct-351_a.png"))); // NOI18N
        jlImagenRouter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlImagenRouter.setMaximumSize(new java.awt.Dimension(490, 200));
        jlImagenRouter.setPreferredSize(new java.awt.Dimension(531, 18));
        ContenidoTexto.add(jlImagenRouter);

        jlSeparador2.setMaximumSize(new java.awt.Dimension(257, 18));
        jlSeparador2.setMinimumSize(new java.awt.Dimension(257, 18));
        ContenidoTexto.add(jlSeparador2);

        jlTexto.setText("En los siguientes pasos se describe el proceso de instalación.");
        ContenidoTexto.add(jlTexto);
        ContenidoTexto.add(jlPrimerPaso);

        jlSeparador3.setMaximumSize(new java.awt.Dimension(257, 30));
        jlSeparador3.setMinimumSize(new java.awt.Dimension(257, 18));
        ContenidoTexto.add(jlSeparador3);

        jlSiguiente.setText("Presione \"Siguiente\" para continuar...");
        ContenidoTexto.add(jlSiguiente);

        ContenidoTodo.add(ContenidoTexto, java.awt.BorderLayout.CENTER);

        Contenido.add(ContenidoTodo, java.awt.BorderLayout.CENTER);

        add(Contenido, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel ContenidoTexto;
    private javax.swing.JPanel ContenidoTodo;
    private javax.swing.JLabel iconoLabel;
    private javax.swing.JLabel jlImagenRouter;
    private javax.swing.JLabel jlPrimerPaso;
    private javax.swing.JLabel jlSeparador;
    private javax.swing.JLabel jlSeparador2;
    private javax.swing.JLabel jlSeparador3;
    private javax.swing.JLabel jlSiguiente;
    private javax.swing.JLabel jlTexto;
    private javax.swing.JLabel lTitulo;
    // End of variables declaration//GEN-END:variables
}
