/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package es.unavarra.iws.routerinstall.gui;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author aqm
 */
public class Rct351Panel2 extends javax.swing.JPanel {

    /**
     * Creates new form Router1Panel2
     */
    public Rct351Panel2() {
        initComponents();
    }

    /*
    public boolean isCheckBoxSelected() {
        return jCheckBox1.isSelected();
    }    
    
    public void addCheckBoxActionListener(ActionListener l) {
        jCheckBox1.addActionListener(l);
    } 
    */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jpTitulo = new javax.swing.JPanel();
        jlTexto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jlIcono = new javax.swing.JLabel();
        jpContenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jbError = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jpTitulo.setForeground(java.awt.Color.gray);
        jpTitulo.setLayout(new java.awt.BorderLayout());

        jlTexto.setBackground(java.awt.Color.lightGray);
        jlTexto.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jlTexto.setText("Conexionado de Módem Comtrend");
        jlTexto.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jlTexto.setOpaque(true);
        jpTitulo.add(jlTexto, java.awt.BorderLayout.CENTER);

        jSeparator1.setBackground(java.awt.Color.lightGray);
        jSeparator1.setOpaque(true);
        jpTitulo.add(jSeparator1, java.awt.BorderLayout.SOUTH);

        jlIcono.setBackground(java.awt.Color.lightGray);
        jlIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/setting32.png"))); // NOI18N
        jlIcono.setOpaque(true);
        jpTitulo.add(jlIcono, java.awt.BorderLayout.LINE_END);

        add(jpTitulo, java.awt.BorderLayout.NORTH);

        jpContenido.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Por favor ingrese el tipo de conector");
        jLabel1.setMaximumSize(new java.awt.Dimension(252, 20));
        jLabel1.setMinimumSize(new java.awt.Dimension(252, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(252, 40));
        jpContenido.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 192));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jRadioButton3.setText("802.11 b/g");
        jPanel1.add(jRadioButton3);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Ethernet RJ-45");
        jPanel1.add(jRadioButton4);

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Ethernet 10 base T");
        jPanel1.add(jRadioButton2);

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Serial/Paralelo");
        jPanel1.add(jRadioButton1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/unavarra/iws/routerinstall/resources/img/attention32.png"))); // NOI18N
        jbError.setText("¿Errores?");
        jbError.setMaximumSize(new java.awt.Dimension(116, 50));
        jbError.setMinimumSize(new java.awt.Dimension(118, 41));
        jbError.setPreferredSize(new java.awt.Dimension(100, 70));
        jbError.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbErrorMouseClicked(evt);
            }
        });
        jbError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbErrorActionPerformed(evt);
            }
        });
        jPanel2.add(jbError, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 80, 120, 40));

        jPanel1.add(jPanel2);
        jPanel1.add(jLabel4);

        jpContenido.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(jpContenido, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jbErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbErrorActionPerformed

    private void jbErrorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbErrorMouseClicked
        //String txtResultado;
        //txtResultado = qm.initInstallationByCharacteristics(txtBusqueda);
        JOptionPane.showMessageDialog(this, "Consulte a su proveedor","En caso de error",JOptionPane.INFORMATION_MESSAGE);
               

    }//GEN-LAST:event_jbErrorMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbError;
    private javax.swing.JLabel jlIcono;
    private javax.swing.JLabel jlTexto;
    private javax.swing.JPanel jpContenido;
    private javax.swing.JPanel jpTitulo;
    // End of variables declaration//GEN-END:variables
}
